name: Build
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: install dependencies
        run: npm ci
      - name: lint check
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: install dependencies
        run: npm ci
      - name: run build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    services:
      stargate:
        image: stargateio/stargate-dse-68:v1.0.15
        env:
          CLUSTER_NAME: stargate
          CLUSTER_VERSION: 6.8
          DEVELOPER_MODE: true
          DSE: 1
        ports:
          - 8080:8080
          - 8081:8081
          - 8082:8082
          - 9042:9042
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: install dependencies
        run: npm ci
      - name: run unit tests
        run: npm run test
      - name: run e2e tests
        run: npm run test:e2e
